### ISSUE TITLE
how to enter multiline input

### ISSUE THREAD

**Issue by timotheecour** [msteveb/linenoise#17]
./linenoise_utf8_example --multiline
[paste several lines of text]
result isn't what I expect (i expected 
echo 'a1
a2
a3'

but insead i just get echo 'a1'

Is there another way to enter multiple lines of text?
(i was hoping for somehing like shift enter etc)

**Comment by msteveb** [comment]
Both multiline and hints are now supported.

Try: ./linenoise_example --multiline
