### ISSUE TITLE
Clearing of characters broken on Windows? (backspace / delete keys)

### ISSUE THREAD

**Issue by CoDEmanX** [msteveb/linenoise#20]
From https://github.com/arangodb/arangodb/issues/1187:

> 1. If you hit backspace with no character entered, `arangosh [...]> ` disappears, and re-appears if you type something in
> 2. If you delete characters and the code wraps to a 2nd line past the length of the string<br>`arangosh [...]> `, the last character won't be cleared and will thus appear as many times as you hit <kbd>Backspace</kbd> / <kbd>Del</kbd>. The superfluous chars are removed as soon as the line length drops low enough (around character 80 of the entered code).
> 
> http://youtu.be/LxQ0zg-fOoY

AFAIK ArangoDB uses https://github.com/antirez/linenoise, so I wonder if it's fixed in this fork?

**Comment by msteveb** [comment]
Thanks for the report. The problem doesn't occur in this fork.
