### ISSUE TITLE
Windows compilation break

### ISSUE THREAD

**Issue by Phytolizer** [msteveb/linenoise#30]
As I'm sure you figured out, I use your fork in a project that has Windows building in CI. Today I updated the repo and compilation broke. I narrowed it down to 7109cc6cdaa20f77283b08f72659aae7677e287d. I'm unable to make a PR fixing this right now, as I'm not sure if this block should be exclusive to non-Windows, or if it should be handled appropriately on both operating systems somehow.

ETA: The reason compilation breaks is that the `fd` field is not defined on Windows.

**Comment by msteveb** [comment]
Thanks for the report. I probably need to set up some ci here too since I don’t normally build for windows. I’ll work out a fix for you.

**Comment by Phytolizer** [comment]
Just verified that 235db62fb43daf9e5a80dd590296efd140d49f47 fixed my build. Thanks!
